### ISSUE TITLE
Installing FFMPEG fails

### ISSUE THREAD

**Issue by Minds3t** [mdhiggins/sma-mod#14]
Tried with latest radarr and sabnzbd all the same issue below:
```
[90-sma-config] Installing additional deluge/qbittorrent requirements
BusyBox v1.36.1 (2023-11-07 18:53:09 UTC) multi-call binary.
Usage: which [-a] COMMAND...
Locate COMMAND
	-a	Show all matches
[90-sma-config] Set FFMPEG URL to https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
[90-sma-config] Downloading and installing FFMpeg from https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
mv: cannot overwrite directory '' with non-directory
mv: cannot overwrite directory '' with non-directory
chown: cannot access '': No such file or directory
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
[ls.io-init] done.
```
This seems to only occur with the docker mod, the pre-build sma radarr image works fine.

**Comment by mdhiggins** [comment]
ec02ba9408d9a5f130e16fa2f03c9ff2e9aa79a2

Hopefully that should fix it, was missing new environment variables

**Comment by Minds3t** [comment]
Looks like it is still not working. (I pulled the new image and re-created the container)

**Comment by mdhiggins** [comment]
Hm, wonder if maybe the mod environment variables don't carry over, vaguely remember running into this issue before, just pushed another update to set the environment variables at the s6 level

1acdfd5e71888306f92c61d313579520f818acc8

**Comment by Minds3t** [comment]
ffmpeg now installs without issues 👍
